apiVersion: v1
kind: Service
metadata:
  name: port-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 443
      nodePort: 30443
      protocol: TCP
      name: https
  selector:
    app: port-app

