# permissions for end users to view ibpconsoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibpconsole-viewer-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibpconsoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibpconsoles/status
  verbs:
  - get
