# permissions for end users to view ibpcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibpca-viewer-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibpcas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibpcas/status
  verbs:
  - get
