# permissions for end users to edit ibpcas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibpca-editor-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibpcas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibpcas/status
  verbs:
  - get
