# permissions for end users to edit ibpconsoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibpconsole-editor-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibpconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibpconsoles/status
  verbs:
  - get
