# permissions for end users to edit ibporderers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibporderer-editor-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibporderers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibporderers/status
  verbs:
  - get
