# permissions for end users to edit ibppeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibppeer-editor-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - ibppeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibp.com
  resources:
  - ibppeers/status
  verbs:
  - get
