#
# Copyright contributors to the Hyperledger Fabric Operator project
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
# 	  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: ibpconsole-deployer-template
data:
  settings.yaml: |
    db:
      connectionurl: "http://localhost:5984"
      createdb: true
      components:
        name: "components"
        designdocs:
        - ./designdocs/components/service_broker.json
        - ./designdocs/components/deployer.json
        - ./designdocs/components/plutus.json
        - ./designdocs/components/search_indices.json
    port: 8080
    loglevel: debug
    tls:
      enabled: false
      certpath: /certs/tls.crt
      keypath: /certs/tls.key
    auth:
      username: dev
      password: dev123

    imagePullSecret: ""
    versions:
      ca:
        1.5.3-1:
          default: true
          version: 1.5.3-1
          image:
            caInitImage: registry.access.redhat.com/ubi8/ubi-minimal
            caInitTag: latest
            caImage: hyperledger/fabric-ca
            caTag: 1.5.3

      peer:
        2.4.3-1:
          default: true
          version: 2.4.3-1
          image:
            peerInitImage: registry.access.redhat.com/ubi8/ubi-minimal
            peerInitTag: latest
            peerImage: hyperledger/fabric-peer
            peerTag: 2.4.3
            couchdbImage: couchdb
            couchdbTag: 3.2.2
            grpcwebImage: ghcr.io/hyperledger-labs/grpc-web
            grpcwebTag: latest
      orderer:
        2.4.3-1:
          default: true
          version: 2.4.3-1
          image:
            ordererInitImage: registry.access.redhat.com/ubi8/ubi-minimal
            ordererInitTag: latest
            ordererImage: hyperledger/fabric-orderer
            ordererTag: 2.4.3
            grpcwebImage: ghcr.io/hyperledger-labs/grpc-web
            grpcwebTag: latest

    defaults:
      storage:
        ca:
          ca:
            size: 1Gi
            class: ""
        peer:
          statedb:
            size: 10Gi
            class: ""
          peer:
            size: 10Gi
            class: ""
        orderer:
          orderer:
            size: 10Gi
            class: ""
      resources:
        ca:
          ca:
            limits:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 1G
            requests:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 100M
          init:
            limits:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 1G
            requests:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 100M
        peer:
          peer:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 200m
              memory: 400M
          couchdb:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 200m
              memory: 400M
          proxy:
            limits:
              cpu: 100m
              memory: 200M
            requests:
              cpu: 100m
              memory: 200M
          init:
            limits:
              cpu: 100m
              memory: 200M
            requests:
              cpu: 100m
              memory: 200M
          chaincodelauncher:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 200m
              memory: 400M
        orderer:
          orderer:
            limits:
              cpu: 250m
              memory: 500M
              ephemeral-storage: 1G
            requests:
              cpu: 250m
              memory: 500M
              ephemeral-storage: 100M
          proxy:
            limits:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 1G
            requests:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 100M
          init:
            limits:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 1G
            requests:
              cpu: 100m
              memory: 200M
              ephemeral-storage: 100M
