name: Build Operator image

on:
  pull_request:
    branches: [main]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          scripts/install-tools.sh
          make image
